
import React, { useState, useEffect } from "react";
import { styles } from "./styles";
import { Transaction, Student, HOSPITALS, BOARD_PROGRAM_MAP, Campus, INITIAL_TEACHERS, StudentAttendance } from "./types";

export const ReportsModule = ({ students, transactions, masterData, subTab, currentUser, studentAttendance = [], setStudentAttendance }: any) => {
   const [activeTab, setActiveTab] = useState(subTab || "defaulters");
   
   useEffect(() => { if(subTab) setActiveTab(subTab); }, [subTab]);

   const [prog, setProg] = useState("All");
   const [sem, setSem] = useState("All");
   const [camp, setCamp] = useState("All");
   const [gender, setGender] = useState("All");
   const [status, setStatus] = useState("All");
   
   // Defaulter specific filter state
   const [selectedBoard, setSelectedBoard] = useState<string | null>(null);
   const [selectedProgram, setSelectedProgram] = useState<string | null>(null);

   const [dateFrom, setDateFrom] = useState(new Date().getFullYear() + "-01-01");
   const [dateTo, setDateTo] = useState(new Date().toISOString().slice(0, 10));

   // Attendance State
   const [attDate, setAttDate] = useState(new Date().toISOString().slice(0, 10));
   const [selectedTeacher, setSelectedTeacher] = useState("All");
   const [viewHistoryMonth, setViewHistoryMonth] = useState(new Date().toISOString().slice(0, 7));
   
   // Exception Based Attendance State
   const [attSearch, setAttSearch] = useState("");
   const [attSelectedIds, setAttSelectedIds] = useState<string[]>([]);
   const [attExceptions, setAttExceptions] = useState<Record<string, "Absent" | "Late" | "Leave">>({});
   const [showAttModal, setShowAttModal] = useState(false);

   // Attendance History Filters
   const [histCampus, setHistCampus] = useState("All");
   const [histProgram, setHistProgram] = useState("All");
   const [histSemester, setHistSemester] = useState("All");
   const [histTeacher, setHistTeacher] = useState("All");

   // Printable Blank Sheet State
   const [showBlankSheet, setShowBlankSheet] = useState(false);

   // Helper for Date Display (DD/MM/YYYY)
   const formatDateDisplay = (dateString: string) => {
       if(!dateString) return "";
       const [y, m, d] = dateString.split('-');
       return `${d}/${m}/${y}`;
   };

   let content = null;

   // Common Print Header Component
   const ReportHeader = ({ title, subTitle }: { title: string, subTitle?: string }) => (
       <div id="printable-area" style={{marginBottom: '20px', display: 'none'}} className="print-header">
           <div style={{textAlign: 'center', marginBottom: '15px', borderBottom: '2px solid #000', paddingBottom: '10px'}}>
               <h1 style={{margin: '0', textTransform: 'uppercase', color: '#000', fontSize: '1.8rem'}}>Ghazali Institute of Medical Sciences</h1>
               <div style={{fontSize: '1.2rem', fontWeight: 600, marginTop: '5px'}}>{title}</div>
               {subTitle && <div style={{fontSize: '1rem', marginTop: '2px'}}>{subTitle}</div>}
           </div>
           <div style={{display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', color: '#333', marginBottom: '15px'}}>
               <div>Generated By: <strong>{currentUser || 'System'}</strong></div>
               <div>Date: {new Date().toLocaleDateString()} | Time: {new Date().toLocaleTimeString()}</div>
           </div>
       </div>
   );

   const filteredStudents = students.filter((s: Student) => {
       if(prog !== "All" && s.program !== prog) return false;
       if(sem !== "All" && s.semester !== sem) return false;
       if(camp !== "All" && s.campus !== camp) return false;
       // Only active students for attendance
       if(s.status === "Left Student" || s.status === "Course Completed") return false;
       return true;
   });

   // Attendance Functions (Exception Based)
   const handleAttSearchSelect = (id: string) => {
       if(attSelectedIds.includes(id)) {
           setAttSelectedIds(attSelectedIds.filter(sid => sid !== id));
       } else {
           setAttSelectedIds([...attSelectedIds, id]);
       }
   };

   const markSelected = (status: "Absent" | "Late" | "Leave") => {
       const newExceptions = { ...attExceptions };
       attSelectedIds.forEach(id => {
           newExceptions[id] = status;
       });
       setAttExceptions(newExceptions);
       setAttSelectedIds([]);
       setAttSearch(""); 
   };

   const removeException = (id: string) => {
       const newExceptions = { ...attExceptions };
       delete newExceptions[id];
       setAttExceptions(newExceptions);
   };

   const saveStudentAttendance = () => {
       if(filteredStudents.length === 0) return alert("No students to mark.");
       
       const record: StudentAttendance = {
           id: `${attDate}-${prog}-${sem}-${camp}`,
           date: attDate,
           campus: camp,
           program: prog,
           semester: sem,
           teacher: selectedTeacher,
           records: filteredStudents.map((s: Student) => ({
               studentId: s.admissionNo,
               name: s.name,
               status: attExceptions[s.admissionNo] || "Present", // Auto-Present
               remarks: ""
           }))
       };

       const others = studentAttendance.filter((a: StudentAttendance) => a.id !== record.id);
       setStudentAttendance([...others, record]);
       alert(`Attendance Saved! ${Object.keys(attExceptions).length} Exceptions, ${filteredStudents.length - Object.keys(attExceptions).length} Present.`);
       setAttExceptions({});
       setShowAttModal(false);
   };

   const filteredAttSearch = filteredStudents.filter((s: Student) => 
       (s.name.toLowerCase().includes(attSearch.toLowerCase()) || s.admissionNo.toLowerCase().includes(attSearch.toLowerCase()))
   );

   // Main Blank Sheet Print View
   if (showBlankSheet) {
       const daysInMonth = 31; 
       return (
           <div style={{background: 'white', padding: '20px', minHeight: '100vh', position: 'fixed', top: 0, left: 0, width: '100%', zIndex: 2000, overflow: 'auto'}}>
               <div className="no-print" style={{marginBottom: '20px', display: 'flex', justifyContent: 'space-between'}}>
                   <button style={styles.button("secondary")} onClick={() => setShowBlankSheet(false)}>Back</button>
                   <button style={styles.button("primary")} onClick={() => window.print()}>Print Register</button>
               </div>
               <div id="printable-area" style={{fontFamily: 'Arial, sans-serif', fontSize: '10px'}}>
                   <div style={{textAlign: 'center', marginBottom: '10px'}}>
                       <h1 style={{margin: 0, textTransform: 'uppercase'}}>Ghazali Institute of Medical Sciences</h1>
                       <h3 style={{margin: '5px 0'}}>Attendance Register</h3>
                       <div style={{display: 'flex', justifyContent: 'center', gap: '20px', fontWeight: 'bold'}}>
                           <span>Program: {prog}</span>
                           <span>Semester: {sem}</span>
                           <span>Campus: {camp}</span>
                           <span>Month: {viewHistoryMonth}</span>
                       </div>
                   </div>
                   <table style={{width: '100%', borderCollapse: 'collapse', border: '1px solid black'}}>
                       <thead>
                           <tr>
                               <th style={{border: '1px solid black', padding: '2px', width: '30px'}}>#</th>
                               <th style={{border: '1px solid black', padding: '2px'}}>Name</th>
                               <th style={{border: '1px solid black', padding: '2px'}}>Father Name</th>
                               <th style={{border: '1px solid black', padding: '2px'}}>Adm No</th>
                               {Array.from({length: daysInMonth}, (_, i) => (
                                   <th key={i} style={{border: '1px solid black', padding: '2px', width: '20px', textAlign: 'center'}}>{i+1}</th>
                               ))}
                           </tr>
                       </thead>
                       <tbody>
                           {filteredStudents.map((s, i) => (
                               <tr key={s.admissionNo}>
                                   <td style={{border: '1px solid black', padding: '4px', textAlign: 'center'}}>{i+1}</td>
                                   <td style={{border: '1px solid black', padding: '4px'}}>{s.name}</td>
                                   <td style={{border: '1px solid black', padding: '4px'}}>{s.fatherName}</td>
                                   <td style={{border: '1px solid black', padding: '4px', textAlign: 'center'}}>{s.admissionNo}</td>
                                   {Array.from({length: daysInMonth}, (_, i) => (
                                       <td key={i} style={{border: '1px solid black', height: '20px'}}></td>
                                   ))}
                               </tr>
                           ))}
                           {Array.from({length: 5}, (_, i) => (
                               <tr key={`empty-${i}`}>
                                   <td style={{border: '1px solid black', height: '25px'}}></td>
                                   <td style={{border: '1px solid black'}}></td>
                                   <td style={{border: '1px solid black'}}></td>
                                   <td style={{border: '1px solid black'}}></td>
                                   {Array.from({length: daysInMonth}, (_, i) => <td key={i} style={{border: '1px solid black'}}></td>)}
                               </tr>
                           ))}
                       </tbody>
                   </table>
                   <div style={{marginTop: '40px', display: 'flex', justifyContent: 'space-between', padding: '0 50px'}}>
                       <div style={{borderTop: '1px solid black', width: '200px', textAlign: 'center'}}>Teacher Signature</div>
                       <div style={{borderTop: '1px solid black', width: '200px', textAlign: 'center'}}>Principal Signature</div>
                   </div>
               </div>
           </div>
       );
   }

   if(activeTab === "defaulters") {
      // ... (Same logic as before, just update date display if any) ...
      const allDefaulters = students.filter((s: Student) => s.balance > 0);
      let filteredList = allDefaulters;
      if(prog !== "All") filteredList = filteredList.filter((s:Student) => s.program === prog);
      if(sem !== "All") filteredList = filteredList.filter((s:Student) => s.semester === sem);
      if(camp !== "All") filteredList = filteredList.filter((s:Student) => s.campus === camp);
      if(selectedBoard) {
          filteredList = filteredList.filter((s:Student) => s.board === selectedBoard);
          if(selectedProgram) filteredList = filteredList.filter((s:Student) => s.program === selectedProgram);
      }
      filteredList.sort((a:Student,b:Student) => b.balance - a.balance);
      const totalDefaulterAmount = filteredList.reduce((acc:number, s:Student) => acc + s.balance, 0);
      const boardStats: any = {};
      filteredList.forEach((s:Student) => {
          if(!boardStats[s.board]) boardStats[s.board] = { count: 0, amount: 0 };
          boardStats[s.board].count++;
          boardStats[s.board].amount += s.balance;
      });
      const programStats: any = {};
      if(selectedBoard) {
          filteredList.filter((s:Student) => s.board === selectedBoard).forEach((s:Student) => {
               if(!programStats[s.program]) programStats[s.program] = { count: 0, amount: 0 };
               programStats[s.program].count++;
               programStats[s.program].amount += s.balance;
          });
      }

      content = (
         <div id="printable-area">
            <ReportHeader title="Defaulters List" subTitle={selectedBoard ? `${selectedBoard} - ${selectedProgram || 'All Programs'}` : 'All Defaulters'} />
            <div className="no-print" onClick={() => { setSelectedBoard(null); setSelectedProgram(null); }} style={{...styles.card, padding: '20px', cursor: 'pointer', background: !selectedBoard ? '#f0f9ff' : 'white', border: !selectedBoard ? '2px solid #0ea5e9' : '1px solid #e2e8f0', marginBottom: '20px', textAlign: 'center', maxWidth: '300px', margin: '0 auto 20px auto'}}>
                <div style={{fontSize: '0.9rem', color: '#64748b', textTransform: 'uppercase', letterSpacing: '1px'}}>Total Outstanding</div>
                <div style={{fontWeight: 800, fontSize: '1.8rem', color: '#0ea5e9'}}>Rs {totalDefaulterAmount.toLocaleString()}</div>
                <div style={{fontSize: '0.8rem', color: '#94a3b8'}}>{filteredList.length} Students</div>
            </div>
            <div className="no-print" style={{display: 'flex', gap: '15px', marginBottom: '20px', flexWrap: 'wrap', justifyContent: 'center'}}>
                {Object.keys(boardStats).map(board => (
                   <div key={board} onClick={() => { setSelectedBoard(board); setSelectedProgram(null); }} style={{...styles.card, padding: '15px', width: '220px', cursor: 'pointer', background: selectedBoard === board ? '#fff7ed' : 'white', border: selectedBoard === board ? '2px solid #f97316' : '1px solid #e2e8f0', marginBottom: 0}}>
                      <div style={{fontSize: '0.8rem', color: '#64748b', fontWeight: 600, height: '40px'}}>{board}</div>
                      <div style={{fontWeight: 700, fontSize: '1.2rem', color: '#c2410c'}}>Rs {boardStats[board].amount.toLocaleString()}</div>
                      <div style={{fontSize: '0.75rem', color: '#94a3b8'}}>{boardStats[board].count} Students</div>
                   </div>
                ))}
            </div>
            {selectedBoard && (
                <div className="no-print" style={{padding: '20px', background: '#f8fafc', borderRadius: '12px', marginBottom: '20px', border: '1px solid #e2e8f0'}}>
                    <div style={{marginBottom: '10px', fontSize: '0.9rem', color: '#64748b', fontWeight: 600}}>Programs in {selectedBoard}:</div>
                    <div style={{display: 'flex', gap: '10px', flexWrap: 'wrap'}}>
                        {Object.keys(programStats).map(prog => (
                            <div key={prog} onClick={() => setSelectedProgram(prog === selectedProgram ? null : prog)} style={{padding: '10px 15px', borderRadius: '8px', cursor: 'pointer', background: selectedProgram === prog ? '#f0fdf4' : 'white', border: selectedProgram === prog ? '2px solid #22c55e' : '1px solid #cbd5e1', boxShadow: '0 1px 2px rgba(0,0,0,0.05)', minWidth: '140px'}}>
                                <div style={{fontSize: '0.8rem', fontWeight: 600, color: '#334155'}}>{prog}</div>
                                <div style={{fontWeight: 700, color: '#15803d'}}>Rs {programStats[prog].amount.toLocaleString()}</div>
                            </div>
                        ))}
                    </div>
                </div>
            )}
            <table style={styles.table}><thead><tr style={{background: '#fff1f2'}}><th style={styles.th}>S.No</th><th style={styles.th}>Name</th><th style={styles.th}>Father</th><th style={styles.th}>Program</th><th style={styles.th}>Board</th><th style={styles.th}>Phone</th><th style={{...styles.th, textAlign: 'right'}}>Outstanding</th></tr></thead><tbody>{filteredList.map((s: Student, i: number) => (<tr key={s.admissionNo}><td style={styles.td}>{i+1}</td><td style={styles.td}>{s.name}</td><td style={styles.td}>{s.fatherName}</td><td style={styles.td}>{s.program} ({s.semester})</td><td style={styles.td}>{s.board}</td><td style={styles.td}>{s.phone}</td><td style={{...styles.td, textAlign: 'right', color: s.balance > 0 ? '#b91c1c' : '#166534'}}>{s.balance.toLocaleString()}</td></tr>))}</tbody></table>
         </div>
      );
   } else if (activeTab === "students_list") {
      const filtered = students.filter((s: Student) => {
         if(prog !== "All" && s.program !== prog) return false;
         if(sem !== "All" && s.semester !== sem) return false;
         if(camp !== "All" && s.campus !== camp) return false;
         if(gender !== "All" && s.gender !== gender) return false;
         if(status !== "All" && s.status !== status) return false;
         return true;
      });
      content = (
         <div style={styles.card} id="printable-area">
             <ReportHeader title="Student List" subTitle={`${prog !== 'All' ? prog : 'All Programs'} ${sem !== 'All' ? `(${sem})` : ''}`} />
             <div className="no-print" style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px'}}>
                 <h3 style={{margin: 0, color: '#000'}}>Student List</h3>
                 <div style={{color: '#64748b'}}>Total: {filtered.length} Students</div>
             </div>
             <table style={styles.table}>
                <thead>
                    <tr>
                        <th style={styles.th}>S.No</th>
                        <th style={styles.th}>Admission No</th>
                        <th style={styles.th}>Student Name</th>
                        <th style={styles.th}>Father Name</th>
                        <th style={styles.th}>Program</th>
                        <th style={styles.th}>Contact No</th>
                        <th style={styles.th}>Status</th>
                        <th style={styles.th}>Remarks</th>
                    </tr>
                </thead>
                <tbody>
                    {filtered.map((s:Student,i:number)=>(
                        <tr key={s.admissionNo} style={{backgroundColor: i % 2 === 0 ? 'white' : '#f8fafc'}}>
                            <td style={styles.td}>{i+1}</td>
                            <td style={styles.td}>{s.admissionNo}</td>
                            <td style={{...styles.td, fontWeight: 600}}>{s.name}</td>
                            <td style={styles.td}>{s.fatherName}</td>
                            <td style={styles.td}>{s.program} ({s.semester})</td>
                            <td style={styles.td}>{s.phone}</td>
                            <td style={styles.td}>
                                <span style={{
                                    padding: '4px 10px', borderRadius: '12px', fontSize: '0.75rem', fontWeight: 600,
                                    backgroundColor: s.status === 'Paid' ? '#dcfce7' : s.status === 'Free' ? '#fef9c3' : '#f1f5f9',
                                    color: s.status === 'Paid' ? '#166534' : s.status === 'Free' ? '#854d0e' : '#64748b'
                                }}>
                                    {s.status}
                                </span>
                            </td>
                            <td style={styles.td}>{s.remarks}</td>
                        </tr>
                    ))}
                </tbody>
             </table>
         </div>
      );
   } else if (activeTab === "admission_reg") {
      const newAdmissions = students.filter((s: Student) => s.admissionDate && s.admissionDate >= dateFrom && s.admissionDate <= dateTo);
      const totalCollected = newAdmissions.reduce((acc: number, s: Student) => acc + (s.admissionFee || 0), 0);
      content = (
         <div style={styles.card} id="printable-area">
             <ReportHeader title="New Admission Register" subTitle={`${formatDateDisplay(dateFrom)} to ${formatDateDisplay(dateTo)}`} />
             <div className="no-print" style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px'}}>
                 <h3 style={{margin: 0, color: '#000'}}>New Admissions</h3>
                 <div style={{display: 'flex', gap: '20px'}}>
                     <div style={{background: '#f0fdf4', padding: '10px 15px', borderRadius: '8px', color: '#166534', fontWeight: 600}}>Total New Students: {newAdmissions.length}</div>
                     <div style={{background: '#eff6ff', padding: '10px 15px', borderRadius: '8px', color: '#1e40af', fontWeight: 600}}>Adm. Fees: Rs {totalCollected.toLocaleString()}</div>
                 </div>
             </div>
             <table style={styles.table}><thead><tr><th style={styles.th}>S.No</th><th style={styles.th}>Date</th><th style={styles.th}>Adm No</th><th style={styles.th}>Name</th><th style={styles.th}>Father Name</th><th style={styles.th}>Program</th><th style={{...styles.th, textAlign: 'right'}}>Adm Fee</th><th style={styles.th}>Remarks</th></tr></thead><tbody>{newAdmissions.map((s: Student, i: number) => (<tr key={s.admissionNo}><td style={styles.td}>{i+1}</td><td style={styles.td}>{formatDateDisplay(s.admissionDate||'')}</td><td style={styles.td}>{s.admissionNo}</td><td style={styles.td}>{s.name}</td><td style={styles.td}>{s.fatherName}</td><td style={styles.td}>{s.program} ({s.semester})</td><td style={{...styles.td, textAlign: 'right', fontWeight: 600}}>{s.admissionFee.toLocaleString()}</td><td style={styles.td}>{s.remarks}</td></tr>))}</tbody></table>
         </div>
      );
   } else if (activeTab === "hospital_report") {
       // Filter Logic for Hospital Report
       const hospTxns = transactions.filter((t: Transaction) => {
           if (t.status !== "Posted") return false;
           // 1. Fee Collection with specific Hospital Fee
           if (t.details && t.details.hospital > 0) return true;
           // 2. Manual Vouchers (CRV/BRP/JV) where Description contains a Hospital Name
           const desc = t.description.toLowerCase();
           const hasHospitalName = HOSPITALS.some(h => desc.includes(h.toLowerCase()));
           if (hasHospitalName && (t.type === 'CRV' || t.type === 'BRP' || t.type === 'JV')) return true;
           return false;
       });

       const grouped: Record<string, {total: number, txns: any[]}> = {};
       
       // Initialize known hospitals
       HOSPITALS.forEach(h => grouped[h] = {total: 0, txns: []});
       grouped["Other Hospital"] = {total: 0, txns: []}; // Fallback bucket

       hospTxns.forEach((t: Transaction) => {
           let hName = "Other Hospital";
           let amount = 0;

           if (t.details && t.details.hospital > 0) {
               // From Fee Collection
               hName = t.details.hospitalName || "Other Hospital";
               amount = t.details.hospital;
           } else {
               // From Manual Voucher
               const found = HOSPITALS.find(h => t.description.toLowerCase().includes(h.toLowerCase()));
               hName = found || "Other Hospital";
               amount = t.amount;
           }

           if(!grouped[hName]) grouped[hName] = {total: 0, txns: []};
           grouped[hName].total += amount;
           grouped[hName].txns.push({ ...t, calculatedAmount: amount });
       });

       const grandTotal = Object.values(grouped).reduce((acc: number, group: any) => acc + group.total, 0);

       content = (
           <div id="printable-area">
               <ReportHeader title="Hospital Fee Report" />
               <div className="no-print" style={{display: 'flex', gap: '20px', marginBottom: '30px', overflowX: 'auto', paddingBottom: '10px'}}>
                   <div style={{minWidth: '200px', background: '#0f172a', padding: '20px', borderRadius: '12px', color: 'white', display: 'flex', flexDirection: 'column', justifyContent: 'space-between'}}><div style={{fontSize: '0.9rem', opacity: 0.8}}>Grand Total Collection</div><div style={{fontSize: '1.8rem', fontWeight: 700}}>Rs {grandTotal.toLocaleString()}</div></div>
                   {Object.keys(grouped).filter(h => grouped[h].total > 0).map(h => (<div key={h} style={{minWidth: '180px', background: 'white', padding: '15px', borderRadius: '12px', border: '1px solid #e2e8f0', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', boxShadow: '0 2px 4px rgba(0,0,0,0.02)'}}><div style={{fontWeight: 600, color: '#334155'}}>{h}</div><div><div style={{fontSize: '1.2rem', fontWeight: 700, color: '#059669'}}>Rs {grouped[h].total.toLocaleString()}</div><div style={{fontSize: '0.75rem', color: '#64748b'}}>{grouped[h].txns.length} Transactions</div></div></div>))}
               </div>
               <div style={{display: 'flex', flexDirection: 'column', gap: '30px'}}>
                   {Object.keys(grouped).map(h => {
                       if (grouped[h].txns.length === 0) return null;
                       return (
                           <div key={h} style={styles.card}>
                               <div style={{display: 'flex', justifyContent: 'space-between', borderBottom: '2px solid #e2e8f0', paddingBottom: '10px', marginBottom: '10px'}}><div style={{display: 'flex', alignItems: 'center', gap: '10px'}}><span className="material-symbols-outlined" style={{color: '#0ea5e9'}}>local_hospital</span><h3 style={{margin: 0, color: '#0f172a'}}>{h}</h3></div><div style={{fontWeight: 700, color: '#166534', fontSize: '1.1rem'}}>Total: Rs {grouped[h].total.toLocaleString()}</div></div>
                               <table style={styles.table}><thead><tr><th style={styles.th}>S.No</th><th style={styles.th}>Student Name</th><th style={styles.th}>Father Name</th><th style={styles.th}>Technology</th><th style={styles.th}>Semester</th><th style={styles.th}>Date</th><th style={{...styles.th, textAlign: 'right'}}>Hospital Fee</th></tr></thead><tbody>{grouped[h].txns.map((t: any, i:number) => { const s = students.find((st:Student) => st.admissionNo === t.studentId); return (<tr key={t.id}><td style={styles.td}>{i+1}</td><td style={styles.td}>{s ? s.name : (t.studentId || 'Manual Entry')}</td><td style={styles.td}>{s ? s.fatherName : '-'}</td><td style={styles.td}>{s ? s.program : '-'}</td><td style={styles.td}>{s ? s.semester : '-'}</td><td style={styles.td}>{formatDateDisplay(t.date)}</td><td style={{...styles.td, textAlign: 'right', fontWeight: 600}}>{t.calculatedAmount.toLocaleString()}</td></tr>); })}</tbody></table>
                           </div>
                       )
                   })}
               </div>
           </div>
       );
   } else if (activeTab === "student_attendance") {
       // --- STUDENT ATTENDANCE SECTION (Exception Based) ---
       const attendanceHistory = studentAttendance.filter((a: StudentAttendance) => {
           if(viewHistoryMonth && !a.date.startsWith(viewHistoryMonth)) return false;
           if(histCampus !== "All" && a.campus !== histCampus) return false;
           if(histProgram !== "All" && a.program !== histProgram) return false;
           if(histSemester !== "All" && a.semester !== histSemester) return false;
           if(histTeacher !== "All" && a.teacher !== histTeacher) return false;
           return true;
       });

       content = (
           <div>
               <div className="no-print" style={{...styles.card, padding: '20px', marginBottom: '30px'}}>
                   <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px'}}>
                       <h3 style={{margin: 0, color: '#0f172a'}}>Student Attendance Sheet</h3>
                       <div style={{display: 'flex', gap: '10px'}}>
                           <button style={styles.button("secondary")} onClick={() => {
                               if(prog === "All" || sem === "All") return alert("Please select Program and Semester first.");
                               setShowBlankSheet(true);
                           }}>Print Blank Register</button>
                           <button style={styles.button("primary")} onClick={() => setShowAttModal(true)}>
                               <span className="material-symbols-outlined">edit_calendar</span> Mark Attendance
                           </button>
                       </div>
                   </div>
                   
                   <div style={{background: '#f8fafc', padding: '20px', borderRadius: '12px', border: '1px solid #e2e8f0', display: 'flex', gap: '20px', flexWrap: 'wrap'}}>
                       <div><label style={styles.label}>Date</label><input type="date" style={styles.input} value={attDate} onChange={e => setAttDate(e.target.value)} /></div>
                       <div><label style={styles.label}>Campus</label><select style={styles.input} value={camp} onChange={e => setCamp(e.target.value)}><option value="All">All</option>{masterData.campuses.map((c:Campus) => <option key={c.name}>{c.name}</option>)}</select></div>
                       <div><label style={styles.label}>Program</label><select style={styles.input} value={prog} onChange={e => setProg(e.target.value)}><option value="All">All</option>{masterData.programs.map((p:string) => <option key={p}>{p}</option>)}</select></div>
                       <div><label style={styles.label}>Semester</label><select style={styles.input} value={sem} onChange={e => setSem(e.target.value)}><option value="All">All</option>{masterData.semesters.map((s:string) => <option key={s}>{s}</option>)}</select></div>
                       <div><label style={styles.label}>Teacher</label><select style={styles.input} value={selectedTeacher} onChange={e => setSelectedTeacher(e.target.value)}><option value="All">Select Teacher</option>{INITIAL_TEACHERS.map(t => <option key={t}>{t}</option>)}</select></div>
                   </div>

                   {/* Added Preview List */}
                   <div style={{marginTop: '20px', background: 'white', padding: '20px', borderRadius: '12px', border: '1px solid #e2e8f0'}}>
                        <h4 style={{marginTop: 0, color: '#334155'}}>Class List Preview ({filteredStudents.length})</h4>
                        <div style={{maxHeight: '300px', overflowY: 'auto'}}>
                            <table style={styles.table}>
                                <thead>
                                    <tr>
                                        <th style={styles.th}>S.No</th>
                                        <th style={styles.th}>Name</th>
                                        <th style={styles.th}>Father Name</th>
                                        <th style={styles.th}>Admission No</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {filteredStudents.length > 0 ? filteredStudents.map((s, idx) => (
                                        <tr key={s.admissionNo}>
                                            <td style={styles.td}>{idx + 1}</td>
                                            <td style={styles.td}>{s.name}</td>
                                            <td style={styles.td}>{s.fatherName}</td>
                                            <td style={styles.td}>{s.admissionNo}</td>
                                        </tr>
                                    )) : (
                                        <tr><td colSpan={4} style={{textAlign: 'center', padding: '20px', color: '#94a3b8'}}>Select Program and Semester to view students</td></tr>
                                    )}
                                </tbody>
                            </table>
                        </div>
                   </div>
               </div>

               {/* Attendance History List */}
               <div style={{marginTop: '40px'}} className="no-print">
                   <h3 style={{color: '#0f172a', borderBottom: '2px solid #e2e8f0', paddingBottom: '10px'}}>Attendance History</h3>
                   <div style={{background: '#fef3c7', padding: '20px', borderRadius: '12px', border: '1px solid #fcd34d', marginBottom: '20px'}}>
                       <h4 style={{marginTop: 0, color: '#92400e'}}>Filters</h4>
                       <div style={{display: 'flex', gap: '15px', flexWrap: 'wrap'}}>
                           <select style={{...styles.input, width: 'auto'}} value={histCampus} onChange={e => setHistCampus(e.target.value)}><option value="All">All Campuses</option>{masterData.campuses.map((c:Campus) => <option key={c.name}>{c.name}</option>)}</select>
                           <select style={{...styles.input, width: 'auto'}} value={histProgram} onChange={e => setHistProgram(e.target.value)}><option value="All">All Programs</option>{masterData.programs.map((p:string) => <option key={p}>{p}</option>)}</select>
                           <select style={{...styles.input, width: 'auto'}} value={histSemester} onChange={e => setHistSemester(e.target.value)}><option value="All">All Semesters</option>{masterData.semesters.map((s:string) => <option key={s}>{s}</option>)}</select>
                           <input type="month" style={{...styles.input, width: 'auto'}} value={viewHistoryMonth} onChange={e => setViewHistoryMonth(e.target.value)} />
                       </div>
                   </div>

                   <div>
                       {attendanceHistory.map(h => (
                           <div key={h.id} style={{padding: '15px', background: 'white', borderRadius: '8px', border: '1px solid #e2e8f0', display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px'}}>
                               <div>
                                   <div style={{fontWeight: 700, color: '#334155'}}>{formatDateDisplay(h.date)}</div>
                                   <div style={{fontSize: '0.85rem', color: '#64748b'}}>{h.program} ({h.semester}) - {h.campus}</div>
                               </div>
                               <div style={{textAlign: 'right'}}>
                                   <div style={{fontSize: '0.9rem', color: '#166534', fontWeight: 600}}>Present: {h.records.filter(r => r.status === 'Present').length}</div>
                                   <div style={{fontSize: '0.9rem', color: '#b91c1c', fontWeight: 600}}>Absent: {h.records.filter(r => r.status === 'Absent').length}</div>
                               </div>
                           </div>
                       ))}
                   </div>
               </div>

               {/* MARK ATTENDANCE MODAL (Exception Based) */}
               {showAttModal && (
                   <div style={styles.modalOverlay}>
                       <div style={{...styles.modalContent, width: '900px', height: '80vh', display: 'flex', flexDirection: 'column'}}>
                           <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px'}}>
                               <h3 style={{margin: 0}}>Mark Class Attendance</h3>
                               <button onClick={() => setShowAttModal(false)} style={{background: 'transparent', border: 'none', cursor: 'pointer'}}>✕</button>
                           </div>
                           <div style={{background: '#f0f9ff', padding: '15px', borderRadius: '8px', marginBottom: '20px', fontSize: '0.9rem', color: '#0369a1', border: '1px solid #bae6fd'}}>
                               <strong>Note:</strong> All {filteredStudents.length} students are marked <strong>PRESENT</strong> by default. Search and select only those who are Absent/Late/Leave.
                           </div>
                           <div style={{display: 'flex', gap: '20px', flex: 1, minHeight: 0}}>
                               <div style={{flex: 1, display: 'flex', flexDirection: 'column', borderRight: '1px solid #e2e8f0', paddingRight: '20px'}}>
                                   <input style={{...styles.input, marginBottom: '10px'}} placeholder="Search Student by Name or Admission No..." value={attSearch} onChange={e => setAttSearch(e.target.value)} autoFocus />
                                   <div style={{flex: 1, overflowY: 'auto', border: '1px solid #eee', borderRadius: '8px'}}>
                                       {attSearch && filteredAttSearch.map(s => (
                                           <div key={s.admissionNo} onClick={() => handleAttSearchSelect(s.admissionNo)} style={{padding: '10px', borderBottom: '1px solid #f1f5f9', cursor: 'pointer', background: attSelectedIds.includes(s.admissionNo) ? '#eff6ff' : 'white', display: 'flex', justifyContent: 'space-between'}}>
                                               <div><div style={{fontWeight: 600}}>{s.name}</div><div style={{fontSize: '0.8rem', color: '#64748b'}}>{s.admissionNo}</div></div>
                                               {attSelectedIds.includes(s.admissionNo) && <span style={{color: '#3b82f6'}}>✓</span>}
                                           </div>
                                       ))}
                                   </div>
                                   <div style={{marginTop: '10px', display: 'flex', gap: '5px'}}>
                                       <button onClick={() => markSelected('Absent')} disabled={attSelectedIds.length === 0} style={{...styles.button("danger"), flex: 1, justifyContent: 'center'}}>Mark Absent</button>
                                       <button onClick={() => markSelected('Leave')} disabled={attSelectedIds.length === 0} style={{...styles.button("secondary"), background: '#3b82f6', color: 'white', flex: 1, justifyContent: 'center'}}>Mark Leave</button>
                                       <button onClick={() => markSelected('Late')} disabled={attSelectedIds.length === 0} style={{...styles.button("secondary"), background: '#f59e0b', color: 'white', flex: 1, justifyContent: 'center'}}>Mark Late</button>
                                   </div>
                               </div>
                               <div style={{flex: 1, display: 'flex', flexDirection: 'column'}}>
                                   <h4 style={{marginTop: 0, color: '#334155'}}>Exceptions ({Object.keys(attExceptions).length})</h4>
                                   <div style={{flex: 1, overflowY: 'auto', background: '#f8fafc', borderRadius: '8px', padding: '10px'}}>
                                       {Object.entries(attExceptions).map(([id, status]) => {
                                           const s = students.find(st => st.admissionNo === id);
                                           return (
                                               <div key={id} style={{background: 'white', padding: '10px', marginBottom: '8px', borderRadius: '6px', border: '1px solid #e2e8f0', display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}>
                                                   <div><div style={{fontWeight: 600}}>{s?.name}</div><span style={{fontSize: '0.8rem', padding: '2px 6px', borderRadius: '4px', background: status === 'Absent' ? '#fee2e2' : status === 'Late' ? '#fef08a' : '#fff7ed', color: status === 'Absent' ? '#b91c1c' : status === 'Late' ? '#a16207' : '#c2410c'}}>{status}</span></div>
                                                   <button onClick={() => removeException(id)} style={{border: 'none', background: 'transparent', cursor: 'pointer', color: '#94a3b8'}}>✕</button>
                                               </div>
                                           )
                                       })}
                                   </div>
                                   <button onClick={saveStudentAttendance} style={{...styles.button("primary"), marginTop: '20px', width: '100%', justifyContent: 'center'}}>Submit Attendance</button>
                               </div>
                           </div>
                       </div>
                   </div>
               )}
           </div>
       );
   }

   const handleExport = (type: string) => {
      alert(`Exporting ${activeTab} to ${type}... (Feature mocked)`);
   };

   return (
      <div>
         <h2 className="no-print" style={{marginBottom: '5px'}}>Reports: <span style={{color: '#64748b', fontSize: '1.2rem', fontWeight: 400}}>{activeTab.replace('_', ' ').toUpperCase()}</span></h2>
         
         <div className="no-print" style={{...styles.card, display: 'flex', gap: '15px', flexWrap: 'wrap', alignItems: 'center'}}>
            <div style={{display: 'flex', gap: '5px', marginRight: '15px'}}>
               <button onClick={() => setActiveTab("defaulters")} style={{...styles.tabButton(activeTab === "defaulters")}}>Defaulters</button>
               <button onClick={() => setActiveTab("students_list")} style={{...styles.tabButton(activeTab === "students_list")}}>Students List</button>
               <button onClick={() => setActiveTab("admission_reg")} style={{...styles.tabButton(activeTab === "admission_reg")}}>Admission Reg</button>
               <button onClick={() => setActiveTab("hospital_report")} style={{...styles.tabButton(activeTab === "hospital_report")}}>Hospital Report</button>
               <button onClick={() => setActiveTab("student_attendance")} style={{...styles.tabButton(activeTab === "student_attendance")}}>Student Attendance</button>
            </div>

            {activeTab === "admission_reg" ? (
               <>
                  <div><label style={styles.label}>From</label><input type="date" style={styles.input} value={dateFrom} onChange={e => setDateFrom(e.target.value)} /></div>
                  <div><label style={styles.label}>To</label><input type="date" style={styles.input} value={dateTo} onChange={e => setDateTo(e.target.value)} /></div>
               </>
            ) : activeTab === "hospital_report" ? (
               <div style={{color: '#64748b'}}>Hospital Fee Collection Summary</div>
            ) : activeTab === "student_attendance" ? (
               <div style={{color: '#64748b'}}>Daily Class Attendance Management</div>
            ) : (
               <>
                  <select style={{...styles.input, width: 'auto'}} value={prog} onChange={e => setProg(e.target.value)}><option value="All">All Programs</option>{masterData.programs.map((p:string) => <option key={p}>{p}</option>)}</select>
                  <select style={{...styles.input, width: 'auto'}} value={sem} onChange={e => setSem(e.target.value)}><option value="All">All Semesters</option>{masterData.semesters.map((s:string) => <option key={s}>{s}</option>)}</select>
                  <select style={{...styles.input, width: 'auto'}} value={camp} onChange={e => setCamp(e.target.value)}><option value="All">All Campuses</option>{masterData.campuses.map((c: Campus) => <option key={c.name}>{c.name}</option>)}</select>
                  
                  {activeTab === 'students_list' && (
                     <>
                        <select style={{...styles.input, width: 'auto'}} value={gender} onChange={e => setGender(e.target.value)}><option value="All">All Genders</option><option>Male</option><option>Female</option></select>
                        <select style={{...styles.input, width: 'auto'}} value={status} onChange={e => setStatus(e.target.value)}><option value="All">All Statuses</option><option>Free</option><option>Paid</option><option>Course Completed</option><option>Left Student</option></select>
                     </>
                  )}
               </>
            )}
            <div style={{marginLeft: 'auto', display: 'flex', gap: '10px'}}>
               <button style={styles.button("secondary")} onClick={() => handleExport('PDF')}><span className="material-symbols-outlined">picture_as_pdf</span> PDF</button>
               <button style={styles.button("secondary")} onClick={() => handleExport('Excel')}><span className="material-symbols-outlined">table_view</span> Excel</button>
               <button style={styles.button("secondary")} onClick={() => window.print()}><span className="material-symbols-outlined">print</span> Print</button>
            </div>
         </div>

         <style>{`
             @media print {
                 .print-header { display: block !important; }
             }
         `}</style>

         {/* Render content based on tab */}
         {content}
      </div>
   );
};
